Hello microverse
ali-techworld/Hello-Microverse pull request #1
Opened 2023-06-05 22:29 UTC by ali-techworld

Creating a Microverse project using

- Index.html
- style.css

2023-06-05 22:44 UTC, levy002 requested changes
## Hello @ali-techworld  , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
- Well-detailed PR title and summary :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure to set up Linters correctly so it runs to check if there are no errors on your pull request. I recommend you take a step back and read this[ lesson](https://github.com/microverseinc/linters-config/blob/master/html-css) to understand it clearly and follow the guideline to set it correctly.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-05 22:44 UTC, levy002 commented on test.md
> +This file should be ignored by git
- [ ] Kindly make sure this `test.md` file which was added in the `gitignore` file is not present in the repository. The reason why we add any file in the `gitgnore` file is that we don't want that file to be pushed on the repository or to not be present in the repo. Kindly make sure to remove it from as it was added in your `gitignore` file.

2023-06-05 22:44 UTC, levy002 commented on README.md
> +
- [ ] Kindly make sure to remove this instruction on how to fill the project information in your Readme. In order to have a clean and professional repo, all this text must be removed. Kindly fix it.

2023-06-05 22:44 UTC, levy002 commented on README.md
> +> Describe the tech stack and include only the relevant sections that apply to your project.
- [ ] Kindly make sure to remove this instruction on how to fill the project information in your Readme. In order to have a clean and professional repo, all this text must be removed. Kindly fix it.

2023-06-05 22:44 UTC, levy002 commented on README.md
> +> Describe between 1-3 key features of the application.
- [ ] Kindly make sure to remove this instruction on how to fill the project information in your Readme. In order to have a clean and professional repo, all this text must be removed. Kindly fix it.

2023-06-05 22:44 UTC, levy002 commented on README.md
> +> Describe how a new developer could make use of your project.
- [ ] Kindly make sure to remove this instruction on how to fill the project information in your Readme. In order to have a clean and professional repo, all this text must be removed. Kindly fix it.

2023-06-05 22:44 UTC, levy002 commented on README.md
> +> Describe 1 - 3 features you will add to the project.
- [ ] Kindly make sure to remove this instruction on how to fill the project information in your Readme. In order to have a clean and professional repo, all this text must be removed. Kindly fix it.

2023-06-05 22:44 UTC, levy002 commented on README.md
> +
- [ ] Kindly remove this unnecessary text in your Readme in order to keep your repo clean and professional.

2023-06-05 22:44 UTC, levy002 commented on README.md
> +
- [ ] Kindly remove this unnecessary text in your Readme in order to keep your repo clean and professional.

2023-06-06 17:33 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @ali-techworld 

Good job so far implementing the suggested changes!  **_However, there are few things that still need to be fixed. But you are almost there!_** 💪 🏁

![so_close](https://user-images.githubusercontent.com/99715640/211022680-440a1bb1-4281-4acb-8dbc-3442fe509063.gif)

## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Good branch name
- ✅ Descriptive PR and README file
- ✅ Correct Linters


## Required Changes 🛑

_Please check the comments under the review._

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Please check the comments under the review._


Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 17:33 UTC, KanzaTahreem commented on test.md
> +This file should be ignored by git
- [ ] As suggested, please make sure that `test.md` file is not present in the repository if it is added to `.gitignore`. 
One possible reason could be that `test.md` file was previously committed and pushed to the remote repository ⛏In this case, adding it to the `.gitignore` file will not automatically remove it from the repository's history, and git will continue to track the file regardless of its inclusion in the `.gitignore`. Please go through [this article](https://stackoverflow.com/questions/7927230/remove-directory-from-remote-repository-after-adding-them-to-gitignore) to learn how to remove committed files ✨💪

2023-06-06 17:33 UTC, KanzaTahreem commented on README.md
> +- GitHub: [@ali-techworld](https://github.com/ali-techworld)
- [OPTIONAL] Well done for implementing the suggested README changes 🥇🥇 I noticed that **_Authors_** section heading is not present in the README 😓 Can you please consider adding the section heading for Author(s) for maintaining a consistency throughout the README ? It will also reflect your detail oriented approach which is always a plus point for a developer 😎

2023-06-06 18:16 UTC, Shisui6 approved these changes
Hi @ali-techworld, 

# Approved 🪄
Your project is complete! There is nothing else to say other than... it's time to merge it 💎
Congratulations! 🎉 

## Highlights 🎯
- Descriptive PR title and summary ✅
- Follows Github flow ✅
- Good commit messages ✅

## Optional suggestions 🪶

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 19:28 UTC, merged